.github/workflows/auto-update.yml
.github/workflows/manual-update.yml
src/Fetchers/TMSFetcher/TMSFetcher.ts
src/Main.ts

Added support for World Masters Hockey Altius to tool
- Added new fetcher for WMH Altius
- Added workflow to pull events
- Added to front end
- Added some clearer logging to NPM flow to differentiate multiple TMS sources

Add World Masters Hockey events

---

docs/app.js

- Origin is now always appended to the URL.

Always add origin to URL

---

docs/app.js

- Fix bug where the fetcher loads an empty screen when an invalid ID is set in the hash.

Fetcher on load

---

src/Fetchers/TMSFetcher/TMSMatchFetcher.ts

Closes #65 
- Stripped all non-numeric characters from index string before parsing to `Number()` function.

Fix match index being NaN for TMS matches

---

src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts

Closes #66 
- If fetching official KNHB matches, sort the order by date-time, since that's not done by default.

Reverse order of KNHB matches with status official

---

src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/Objects/Match.ts
src/Utils/Abbreviations.ts
tests/src/Objects/Match.test.ts

Closes #72 
- Add toggle to change whether the match index should be included in the generated ICS.
- Set the toggle to false for KNHB matches.
- Added test cases for this.

Remove index from KNHB matches

---

src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/Fetchers/TMSFetcher/TMSMatchFetcher.ts
src/Objects/Match.ts
src/Utils/DateHelper.ts
tests/src/Objects/Match.test.ts
tests/src/Utils/DateHelper.test.ts

Closes #71 
- Added the timeKnown flag to the matches. If set to false, an all-day event is returned.
- Added a check for KNHB matches whether the time is known.

Add all-day event for KNHB matches with no set time.

---

src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts

Fix try-count not correct

---

src/Fetchers/Fetcher.ts
src/Fetchers/KNHBFetcher/KNHBClubFetcher.ts
src/Fetchers/KNHBFetcher/KNHBCompetitionFetcher.ts
src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/Fetchers/TMSFetcher/TMSCompetitionFetcher.ts
src/Fetchers/TMSFetcher/TMSMatchFetcher.ts
src/Utils/APIHelper.ts
tests/src/Utils/APIHelper.test.ts

Closes #76 
- Add global fetch function, with retry implemented.
- Added test cases for this function.
- Changed all fetchers to use new fetch function.

Add retry to all fetch requests

---

docs/app.js
docs/index.html
docs/style.css

Closes #79 
- Add loading spinner to website.

Add loading spinner to website

---

docs/app.js
docs/style.css
src/Fetchers/Fetcher.ts
src/Fetchers/KNHBFetcher/KNHBFetcher.ts
src/Fetchers/TMSFetcher/TMSFetcher.ts
src/Main.ts
src/Utils/ICSCreator.ts
tests/src/Utils/APIHelper.test.ts
tests/src/Utils/Abbreviations.test.ts

Closes #81 
- Add full-name attribute to each fetcher.
- Update fetch selector on website to include full names.

Add full descriptive name to each fetcher

---

src/Fetchers/Fetcher.ts
src/Fetchers/KNHBFetcher/KNHBClubFetcher.ts
src/Fetchers/KNHBFetcher/KNHBFetcher.ts
src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts

Closes #83 
- Add debugging lines to explain KNHB fetch errors.
- Some refactoring.

Improvements to fetcher and add debugging lines

---

src/Fetchers/KNHBFetcher/KNHBClubFetcher.ts
src/Fetchers/KNHBFetcher/KNHBFetcher.ts
src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/Utils/APIHelper.ts
tests/src/Utils/APIHelper.test.ts

Closes #85
- Adjust rate limit delay to match returned header by KNHB API.
- Added safeguard for parsing KNHB club names.

Fix failing KNHB fetcher

---

docs/app.js

Closes #89
- Hide warning when fetcher is closed.

Hide warning on origin close

---

docs/app.js

Thank you for contributing to this application!
**Important**: make sure you create an issue first before submitting a pull request. Replace [ISSUE NUMBER] with the ID of the issue that is solved by this PR.
Closes #91 
- Remove hard-coded check for EH fetcher
- Added check for no clubs.

Hide club select based on club count instead of fetcher type

---

includes/competition-abbreviations.json
tests/includes/competition-abbreviations.json

Thank you for contributing to this application!
**Important**: make sure you create an issue first before submitting a pull request. Replace [ISSUE NUMBER] with the ID of the issue that is solved by this PR.
Closes #97 
- Add abbreviation for the FIH Pro League.

Add competition abbreviation for the FIH Pro League

---

docs/style.css

Closes #99
- Left-align last update when no team selector is visible

Left-align last update when no team selector is visible

---

src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts

Closes #101 
- Check of null when parsing team names.

Fix toLowerCase() on null in KNHB fetcher.

---

package.json
src/Fetchers/TMSFetcher/TMSMatchFetcher.ts
src/Utils/DateHelper.ts
tests/src/Utils/DateHelper.test.ts

Thank you for contributing to this application!
**Important**: make sure you create an issue first before submitting a pull request. Replace [ISSUE NUMBER] with the ID of the issue that is solved by this PR.
Closes #104 
- Attempt to fetch the timezone of the venue location when parsing the date.
- If a timezone is found, use that to convert the date and time.
- If not, fallback to the timezone specified by the FIH.

Add timezone location lookup to prevent wrong timezones

---

src/Fetchers/FIHFetcher/FIHCompetitionFetcher.ts
src/Fetchers/FIHFetcher/FIHFetcher.ts
src/Fetchers/FIHFetcher/FIHMatchFetcher.ts
src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/Fetchers/TMSFetcher/TMSFetcher.ts
src/Main.ts
src/Utils/APIHelper.ts
src/Utils/Abbreviations.ts
src/Utils/DateHelper.ts
tests/src/Utils/DateHelper.test.ts

Closes #114 
- Added an additional fetcher that uses FIH's own API.

Add dedicated FIH fetcher

---

src/Fetchers/FIHFetcher/FIHMatchFetcher.ts

Closes #116 
- Use countries' short name instead of long name to fix clubs not working.

Fix FIH clubs not working

---

includes/match-type-abbreviations.json
src/Fetchers/FIHFetcher/FIHFetcher.ts
src/Fetchers/FIHFetcher/FIHMatchFetcher.ts
tests/includes/match-type-abbreviations.json

Closes #118
- Add correct event stage as match type.
- Add additional match type abbreviations to handle the new FIH fetcher.

Add event stage to FIH matches

---

.gitignore
package.json
src/Fetchers/AltiusFetcher/AltiusCompetitionFetcher.ts
src/Fetchers/AltiusFetcher/AltiusFetcher.ts
src/Fetchers/AltiusFetcher/AltiusMatchFetcher.ts
src/Fetchers/AltiusFetcher/AltiusOfficialFetcher.ts
src/Fetchers/FIHFetcher/FIHFetcher.ts
src/Main.ts
src/Objects/Competition.ts
src/Utils/Abbreviations.ts
src/Utils/DateHelper.ts
tests/src/Fetchers/TMSFetcher/TMSMatchFetcher.test.ts
tests/src/Fetchers/TMSFetcher/TMSOfficialFetcher.test.ts
tests/src/Utils/APIHelper.test.ts
tests/src/Utils/Abbreviations.test.ts
tests/src/Utils/DateHelper.test.ts

Closes #122
- Rename all instances of TMS to Altius
- Fix some other naming errors

Rename old naming conventions

---

src/Fetchers/FIHFetcher/FIHMatchFetcher.ts

Closes #124 
- Replace special characters (URL sanitization)

Fix invalid FIH url

---

src/Fetchers/KNHBFetcher/KNHBFetcher.ts
src/Utils/Abbreviations.ts
tests/src/Utils/Abbreviations.test.ts

Closes #132
- Add support for KNHB mixed gender

Fix KNHB Mixed gender bug

---

.github/workflows/auto-update.yml

Closes #134 
- Add discord webhook on failure

Add Discord notification in case of a failure

---

src/Fetchers/AltiusFetcher/AltiusCompetitionFetcher.ts
src/Fetchers/AltiusFetcher/AltiusMatchFetcher.ts
src/Fetchers/FIHFetcher/FIHCompetitionFetcher.ts
src/Fetchers/FIHFetcher/FIHMatchFetcher.ts
src/Fetchers/Fetcher.ts
src/Fetchers/KNHBFetcher/KNHBCompetitionFetcher.ts
src/Fetchers/KNHBFetcher/KNHBMatchFetcher.ts
src/ICS.ts
src/Main.ts
src/Utils/APIHelper.ts
src/Utils/Abbreviations.ts
src/Utils/ObjectHelper.ts
tests/src/Fetchers/TMSFetcher/TMSMatchFetcher.test.ts
tests/src/Utils/APIHelper.test.ts
tests/src/Utils/Abbreviations.test.ts
tests/src/Utils/ObjectHelper.test.ts

Closes #142 
- Allow for more friendly logging by adding metadata.
- Set the process exit code based on the log types.
- Keep the fetcher running when an error occurs, but skip that competition/match.

Keep fetcher running when an error occurs, but exit with error status.

---

package.json

Bump dependendies to latest version

---

src/Fetchers/Fetcher.ts

Ignore warning messages for the return status code.
